print(" ")
formula1 = (2**6)
print(formula1)
formula2 = (22+(22-3)*3-(99/3))
print(formula2)
print("-------")
print("=",formula1 - formula2)
print(" ")
print("Now that I have tested doing mathematical operations with multiple formuli, I will try to update the value of a signle variable, 'y'.")
y = (6)
print("y equals:",y)
y = (y+2)
print("y now equals:",y)
print(" ")